### ISSUE TITLE
Integration Down: "Failed setup, will retry: 500, message='Internal Server Error"

### ISSUE THREAD

**Issue by sdoowo200leldls** [Pirate-Weather/pirate-weather-ha#272] opened 2024-08-01 06:31 UTC
### Describe the issue

The HA integration is unable to load due to this error. Seems like it occurred in the past here.

https://github.com/Pirate-Weather/pirateweather/issues/208

### Home Assistant version

2024.7.4

### Integration version

1.5.2

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment] 2024-08-01 12:18
This issue occurs on the 1st of the month and fixes itself after a few hours.

The API is now back up and running so this can be closed.

Duplicate of https://github.com/Pirate-Weather/pirateweather/issues/277

**Closed by cloneofghosts** 2024-08-01 12:18 UTC
Labels: duplicate
