### ISSUE TITLE
Hourly Forecast is missing

### ISSUE THREAD

**Issue by clowncracker** [Pirate-Weather/pirate-weather-ha#292] opened 2024-08-17 19:34 UTC
### Describe the issue

It looks like the hourly forecast doesn't show up in the entity anymore.  The daily forecast does, but when I swap to hourly it just shows nothing:

![image](https://github.com/user-attachments/assets/7d808cb3-a580-4bff-9956-0f5c0d797748)

![image](https://github.com/user-attachments/assets/0f4a0681-7513-450b-8576-de7cc77d5d7c)

There are no log issues that I can see.  I tried re-downloading the addon and reconfiguring it, neither helping.

### Home Assistant version

2024.8.2

### Integration version

1.5.6

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

**Comment by jhemak** [comment] 2024-08-17 21:01
For me, it seems related to enormous crazy values for apparent_temperature.

**Comment by clowncracker** [comment] 2024-08-17 21:28
I'm having apparent_temperature issues in my logs:

```Logger: homeassistant.components.websocket_api.messages
Source: components/websocket_api/messages.py:243
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:23:09 PM (91 occurrences)
Last logged: 1:18:14 PM

Unable to serialize to JSON. Bad data found at $.event.forecast[165].apparent_temperature=-11699019371917938688(<class 'int'>, $.event.forecast[166].apparent_temperature=-17275089156067377152(<class 'int'>, $.event.forecast[168].apparent_temperature=-43661333378357624832(<class 'int'>
Unable to serialize to JSON. Bad data found at $.event.forecast[164].apparent_temperature=-11699019371917938688(<class 'int'>, $.event.forecast[165].apparent_temperature=-17275089156067377152(<class 'int'>, $.event.forecast[167].apparent_temperature=-43661333378357624832(<class 'int'>, $.event.forecast[168].apparent_temperature=-64471507816498429952(<class 'int'>```

**Comment by cloneofghosts** [comment] 2024-08-18 16:49
This issue should be fixed now. This was caused by extremely high wind speed (see: https://github.com/Pirate-Weather/pirateweather/issues/294) which in turn affected the apparent_temperature calculation.

**Closed by cloneofghosts** 2024-08-18 16:49 UTC
