### ISSUE TITLE
Upgraded from 1.5 to 1.5.2 now Pirate Weather will not load.

### ISSUE THREAD

**Issue by mattlward** [Pirate-Weather/pirate-weather-ha#242] opened 2024-06-01 04:22 UTC
### Describe the issue

I just finally did the upgrade and lost all pirate weather functionality.  All of my entries indicate Failed setup, will retry.  I have rebooted, tried adding a new integration and tried to verify my api key.  The auth service change on the api page will not send me a reset password code and I can't login!  

I have not been able to figure out how to fall back to 1.5 either.

### Home Assistant version

2024.5.5

### Integration version

1.5.2

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by mattlward** [comment] 2024-06-01 04:45
I was mistaken, was running 1.5 before the update.  I have restored Pirate Weather from my backup yesterday and I am getting the same results.
[home-assistant_pirateweather_2024-06-01T04-20-24.334Z.log](https://github.com/user-attachments/files/15520439/home-assistant_pirateweather_2024-06-01T04-20-24.334Z.log)

**Comment by D34DC3N73R** [comment] 2024-06-01 08:34
I'm' experiencing the same thing. The debug message isn't much help but mousing over the error icon seems to indicate it's a problem with the api servers.
![pirate-api](https://github.com/Pirate-Weather/pirate-weather-ha/assets/9123670/b6903663-0a99-4fc1-bdff-c6026235cedc)

**Comment by cloneofghosts** [comment] 2024-06-01 12:06
This was an API issue that has since been fixed. Duplicate of https://github.com/Pirate-Weather/pirateweather/issues/242

**Closed by cloneofghosts** 2024-06-01 12:06 UTC
Labels: duplicate, invalid

**Comment by mattlward** [comment] 2024-06-01 19:34
Sorry for missing the API issue, what is the best way to verify this going forward?

**Comment by cloneofghosts** [comment] 2024-06-03 14:24
The easiest way to check is to query the API in your browser and see if you get the same issue. If you are then it's likely an API issue and should be reported in the [API Repository](https://github.com/alexander0042/pirate-weather-ha) if not already reported.

Like the screenshot posted above you can go to the integration and mouse over the error icon. If the message says Internal Server Error then the issue is on the APIs end.
