### ISSUE TITLE
Feature Request: Allow Templating in Configuration

### ISSUE THREAD

**Issue by tdvantine** [Pirate-Weather/pirate-weather-ha#46] opened 2022-05-22 19:48 UTC
Currently the entry in configuration.yaml requires you to put your static location in: (broad location used here, yes I understand I could/should use a !secret here, but meh) 
```
weather:
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    # Additional optional values:
    latitude: '39'
    longitude: '-104'
    mode: "daily"
    name: PirateWeather
```
This works wonderful for home use, and I would say a good 95%+ of installations. However, I personally have a outlier case, as well as I am sure those that use HA for their RV or boat, etc would like this as well. I use HA to automate things on a touring show (think theatrical touring) and we are at a different city every week, being able to template the location would be amazing so we could get the weather for what ever city we are in that week.
An example of what the entry would look like:
```
weather:
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    # Additional optional values:
    latitude: {{states.person.<NAME>.attributes.latitude}}
    longitude: {{states.person.<NAME>.attributes.longitude}}
    mode: "daily"
    name: PirateWeather
```

I have found some work-arounds to this, using a rest sensor to poll the api, but this wont do as it polls the api on every update of location instead of every 15mins/configured amount of time in the sensor. 

I have a home instance (HA Core on Ubuntu) and the touring one (HAOS on a Pi) so I would be more than happy and willing to test out anything you need. I am also open to any other ideas to get this working.

**Comment by alexander0042** [comment] 2022-05-24 20:36
Hi,

Thanks for trying out this service and opening this issue! That's a really interesting use case (I love hearing how people are using this service), and definitely something that would be worth adding. 

At the moment, I'm in the middle of a re-write of this entire integration. It started out as just trying to allow setup via the web GUI config flow, but in order to do that the code had to be asynchronous, which led to all sorts of complications! The good news is that I almost have this working, and it should modernize most of the code base here, The way you've described the template it should "just work", but I remain skeptical. 

One quick thing that would help here is if you could try adding a single variable rest sensor, since you've already started down that road a little bit. If you check out this issue: <https://github.com/alexander0042/pirate-weather-ha/issues/4#issuecomment-1129034675>, I have instructions on how to create one for a single variable, Since the rest sensor supports templates (I think), it'd be worth testing that with temperature just to make sure that one part of it is updating.

**Comment by tdvantine** [comment] 2022-05-24 21:03
```
sensor:
  - platform: rest
    name: PW_1Day_Precip
    scan_interval: 15
    resource: https://api.pirateweather.net/forecast/<key>/<lat>,<long>,-86400?units=ca
    value_template: "{{ float(value_json.daily.data[0].precipAccumulation) }}"
    unit_of_measurement: "cm"
```
Is very very similar to the rest sensor I had set up. I will add in the `scan_interval:` and do some testing to see if that clears up the constant api call everytime my location is reported again. Will post back later today with the results and excact code block used. 

I personally find the pirate weather intergration the best one avaible, a lot of the others lack features or you have to pay for them unlike PW.

**Comment by alexander0042** [comment] 2022-05-24 21:16
Thanks, keep me posted!

This sort of feedback is really great to hear- it really bothered me that most weather forecasts come from government agencies, but then we have to go through poorly documented cooperate APIs to access the data, so I wanted to do something to fix it. It shouldn't be such a mystery what AccuWeather means by "percent of precipitation", but it is for some reason! Along the way, the Dark Sky syntax seemed to work perfectly well, and let me leverage a ton of existing code out there (like this integration).

**Comment by tdvantine** [comment] 2022-05-25 04:21
https://twitter.com/kleverlands/status/1338927247126827009?s=20&t=k4Ag7l-W7MY6PPG18cOdbw
```
- platform: rest
  resource_template: !secret pirate_rest_resource
  json_attributes_path: "$.currently"
  scan_interval: '00:15:00'
  json_attributes:
    - summary
    - temperature
    - precip_probability
    - precip_type
    - humidity
    - cloud_cover
    - nearest_storm_distance
    - precip_intensity
    - wind_speed
  name: pirateweather_api_test
  value_template: 'OK'
  ```
Didn't update on the 15min mark, as well as its missing some of the data.
![image](https://user-images.githubusercontent.com/56764154/170178906-b14a132f-6f6e-41f3-a470-fd29c1d5f434.png)
Just noticed as I was typing, the attributes don't line up correctly. So for right this second, its just the update at the 15 min mark that isn't happening

**Comment by tdvantine** [comment] 2022-05-25 04:34
Corrected the JSON Attributes and solved that "problem".
![image](https://user-images.githubusercontent.com/56764154/170180488-e06e042a-0be9-4b80-aa6d-16c25d325897.png)

**Comment by tdvantine** [comment] 2022-05-25 15:27
```
- platform: rest
  resource_template: !secret pirate_rest_resource
  json_attributes_path: "$.currently"
  scan_interval: '00:15:00'
  json_attributes:
    - summary
    - temperature
    - precipProbability
    - precipType
    - humidity
    - cloudCover
    - nearestStormDistance
    - precipIntensity
    - windSpeed
  name: pirateweather_api_test
  value_template: 'OK
```
Updates every 15 mins and does NOT update when the device tracker updates location so that's perfect. Now, too bad it isn't intergrated into a weather entity to use the weather cards. 

The resource:
```
pirate_rest_resource: 'https://dev.pirateweather.net/forecast/<API>/{{states.person.tristan_van_tine.attributes.latitude}},{{states.person.tristan_van_tine.attributes.longitude
```

**Comment by tdvantine** [comment] 2022-05-30 03:50
Been playing around and I believe that using the rest calls just isn't going to work as nicely. Having a hard time getting forecast to show in a weather card.

So far I have this for the weather.dynamic_weather sensor:
```
weather:
  - platform: template
    name: "Dynamic Weather"
    unique_id: 472658229893
    # attribution: "Powered by PirateWeather"
    condition_template: "{{ state_attr('sensor.pirateweather_api_test', 'summary') }}"
    temperature_template: "{{ state_attr('sensor.pirateweather_api_test', 'temperature') | float }}"
    humidity_template: "{{ state_attr('sensor.pirateweather_api_test', 'humidity') | float }}"
    pressure_template: "{{ state_attr('sensor.pirateweather_api_test', 'pressure') }}"
    wind_speed_template: "{{ state_attr('sensor.pirateweather_api_test', 'windSpeed') }}"
    ozone_template: "{{ state_attr('sensor.pirateweather_api_test', 'ozone') }}"
    visibility_template: "{{ state_attr('sensor.pirateweather_api_test', 'visibility') }}"
    forecast_template: "{{ state_attr('pirateweather_api_forcast', 'data') }}"
```
![image](https://user-images.githubusercontent.com/56764154/170913810-8e63606c-daf7-4434-9199-38bae51d204e.png)

Which all pulls in correctly, other than forecast.

I have this working great for current weather conditions:
```
- platform: rest
  resource_template: !secret pirate_rest_resource
  name: pirateweather_api_test
  json_attributes_path: "$.currently"
  scan_interval: '00:15:00'
  json_attributes:
    - summary
    - temperature
    - precipProbability
    - precipType
    - humidity
    - cloudCover
    - nearestStormDistance
    - precipIntensity
    - windSpeed
    - visibility
    - ozone
    - windBearing
    - pressure
  value_template: 'OK'
  ```
  
![image](https://user-images.githubusercontent.com/56764154/170913858-56f68a5d-e65e-41d5-832a-79fbcd1392d5.png)

  
  I tried to combine the call using the below, but it didnt work for the forecast once again:
  ```
  rest:
  - scan_interval: 900
    resource_template: !secret pirate_rest_resource
    sensor:
      - name: "pirateweather_api_current"
        json_attributes_path: "$.currently"
        value_template: "OK"
        json_attributes:
          - summary
          - temperature
          - precipProbability
          - precipType
          - humidity
          - cloudCover
          - nearestStormDistance
          - precipIntensity
          - windSpeed
          - visibility
          - ozone
          - windBearing
          - pressure
      - name: "pirateweather_api_forcast"
        json_attributes_path: "$.daily"
        value_template: "OK"
        json_attributes:
          - data
```
![image](https://user-images.githubusercontent.com/56764154/170913709-00150a49-f253-4021-91e0-61bcf377e5b5.png)
![image](https://user-images.githubusercontent.com/56764154/170913751-11b3ac2a-c6bf-48db-8941-f7fb56fdeca0.png)

**Comment by tdvantine** [comment] 2022-06-25 16:07
Any new info?

**Comment by alexander0042** [comment] 2022-06-28 10:52
Thanks for following up here! I haven't quite gotten the update integration working yet, but it's at the top of my list and shouldn't be too much longer. If you want to follow along with the progress, I've made a [new branch](https://github.com/alexander0042/pirate-weather-ha/tree/dev-config-flow) that will eventually get merged in with the changes. It's super unstable at the moment, but gives an idea of how everything will fit together with the config flow/ async setup, and should addressing the templateing issue at the same time!

**Comment by mikegoubeaux** [comment] 2023-02-23 17:22
I'm also interested in dynamic location weather reports. I love Pirate Weather, but can't figure out if they config supports dynamically updating location. I have a gps sensor updating Home Assistant core location and a device tracker that are available but it seems Pirate Weather location config is static and can only be updated manually. Is there a method for dynamically updating Pirate Weather location?

**Comment by elykrk** [comment] 2023-05-03 20:40
Same here would love to be able to do dynamic location updates! Thanks for your work on this.

**Comment by alexander0042** [comment] 2023-05-15 20:41
As part of the fundamental setup of integration, I don't think possible to change the location dynamically. The issue is that it uses a weather data coordinator that is based on the lat-lon of the setup location, and it sticks with that. 

However, some of the comments above get is to the same place! You can combine the "rest" platform with a weather template to produce the card manually. As a first pass, I have something like this:


```

weather:
  - platform: template
    name: "Dynamic Weather"
    # attribution: "Powered by PirateWeather"
    condition_template: "{{ state_attr('sensor.PW_Template_Currently', 'summary') }}"
    temperature_template: "{{ state_attr('sensor.PW_Template_Currently', 'temperature') | float }}"
    humidity_template: "{{ state_attr('sensor.PW_Template_Currently', 'humidity') | float }}"
    pressure_template: "{{ state_attr('sensor.PW_Template_Currently', 'pressure') }}"
    wind_speed_template: "{{ state_attr('sensor.PW_Template_Currently', 'windSpeed') }}"
    ozone_template: "{{ state_attr('sensor.PW_Template_Currently', 'ozone') }}"
    visibility_template: "{{ state_attr('sensor.PW_Template_Currently', 'visibility') }}"
    forecast_template: >-
      [
        {
          {% set dat = now() + timedelta( days = 0 ) %}
          "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
          "temperature": "{{ state_attr('sensor.PW_Template_Daily0', 'temperatureHigh') | float }}",
          "templow": "{{ state_attr('sensor.PW_Template_Daily0', 'temperatureLow') | float }}",
          "precipitation": "{{ state_attr('sensor.PW_Template_Daily0', 'precipAccumulation') | float }}",
          "condition":  "{{ state_attr('sensor.PW_Template_Daily0', 'summary') }}",
        },
        {
          {% set dat = now() + timedelta( days = 1 ) %}
          "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
          "temperature": "{{ state_attr('sensor.PW_Template_Daily1', 'temperatureHigh') | float }}",
          "templow": "{{ state_attr('sensor.PW_Template_Daily1', 'temperatureLow') | float }}",
          "precipitation": "{{ state_attr('sensor.PW_Template_Daily1', 'precipAccumulation') | float }}",
          "condition":  "{{ state_attr('sensor.PW_Template_Daily1', 'summary') }}",          
        },
        {
          {% set dat = now() + timedelta( days = 2 ) %}
          "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
          "temperature": "{{ state_attr('sensor.PW_Template_Daily2', 'temperatureHigh') | float }}",
          "templow": "{{ state_attr('sensor.PW_Template_Daily2', 'temperatureLow') | float }}",
          "precipitation": "{{ state_attr('sensor.PW_Template_Daily2', 'precipAccumulation') | float }}",
          "condition":  "{{ state_attr('sensor.PW_Template_Daily2', 'summary') }}",          
        }
      ]

rest:
  resource: 'https://api.pirateweather.net/forecast/<PW_API_KEY>/45.4215,-75.697'
  scan_interval: 60
  sensor:
    - name: "PW_Template_Currently"
      json_attributes_path: "$.currently"
      value_template: "OK"
      json_attributes:
        - summary
        - temperature
        - precipProbability
        - precipType
        - humidity
        - cloudCover
        - nearestStormDistance
        - precipIntensity
        - windSpeed
        - visibility
        - ozone
        - windBearing
        - pressure
    - name: "PW_Template_Daily0"
      json_attributes_path: "$.daily.data.[0]"
      value_template: "OK"
      json_attributes:
        - summary
        - temperatureHigh
        - temperatureLow
        - precipAccumulation      
    - name: "PW_Template_Daily1"
      json_attributes_path: "$.daily.data.[1]"
      value_template: "OK"
      json_attributes:
        - summary
        - temperatureHigh
        - temperatureLow
        - precipAccumulation 
    - name: "PW_Template_Daily2"
      json_attributes_path: "$.daily.data.[2]"
      value_template: "OK"
      json_attributes:
        - summary
        - temperatureHigh
        - temperatureLow  
        - precipAccumulation      

```

I'll test this a bit more and see if I can't get the template into the location and flesh out the weather card a bit, but this absolutely should work! The only downside is that it makes we wonder if I should have just done this instead of building a whole integration...

**Comment by mikegoubeaux** [comment] 2023-05-16 19:48
@alexander0042 that's a great solution! I just implemented this with the lat/lon from zone.home (which is updated by GPS sensor via an automation and homeassistant.set_location) for my Van implementation. So, the weather updates as we move from place to place!

Wondering if there is a sensible way to implement this for an hourly forcast for the next 24 hrs?

FWIW: I found I had to remove the "Z" from the forecast_template datetime string for the forecast to show the days correctly as I am (currently) UTC -7

Nice work!

**Comment by tdvantine** [comment] 2023-07-04 02:39
NWS had an update and saw this 

> ...coordinates or you can get dynamic location alerts by configuring the integration to use a device_tracker entity from HA as long as that device tracker provides GPS coordinates.

Perhaps there is something that could help you out in getting a cleaner implementation
https://github.com/finity69x2/nws_alerts

**Comment by tdvantine** [comment] 2023-10-02 12:33
Is this something we are still looking to properly implement, or are we satisfied with the work arounds overall? Plus, will these still work with the HA changes needed for PirateWeather to continue working?

**Comment by breel007** [comment] 2024-03-10 08:56
Thanks @alexander0042 for the starting point.  I think I got it cleaned up quite a bit and got hourly working as well:

# setup pirate weather dynamic location
weather:
  - platform: template
    name: "Dynamic Weather Template"
    unique_id: "pw_template"
    attribution_template: "Powered by Pirate Weather"
    temperature_template: "{{ state_attr('sensor.PW_Template_Currently', 'temperature') | int }}"
    temperature_unit: "°F"
    humidity_template: "{{ state_attr('sensor.PW_Template_Currently', 'humidity')*100 | int }}"
    pressure_template: "{{ state_attr('sensor.PW_Template_Currently', 'pressure') }}"
    pressure_unit: "hPa"
    wind_speed_template: "{{ state_attr('sensor.PW_Template_Currently', 'windSpeed') | int}}"
    wind_speed_unit: "mph"
    ozone_template: "{{ state_attr('sensor.PW_Template_Currently', 'ozone') }}"
    visibility_template: "{{ state_attr('sensor.PW_Template_Currently', 'visibility') }}"
    visibility_unit: "mi"
    precipitation_unit: "in"
    condition_template: >-
      {% if state_attr('sensor.PW_Template_Currently', 'icon') == "clear-night" %}
        clear-night
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "clear-day" %}
        sunny
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "cloudy" %}
        cloudy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "fog" %}
        fog
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "partly-cloudy-day" %}
        partlycloudy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "partly-cloudy-night" %}
        partlycloudy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "rain" %}
        rainy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "snow" %}
        snowy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "sleet" %}
        snowy        
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "wind" %}
        windy                                              
      {% endif %}
    forecast_daily_template: >-
      {%set return=namespace(data=[])%}
      {%for datapoint in state_attr('sensor.forecast_daily', 'data')%}
      {% set condition=datapoint.icon%}
      {% if datapoint.icon == "clear-day" %}
      {%set condition="sunny"%}
      {% elif datapoint.icon == "partly-cloudy-day" or datapoint.icon == "partly-cloudy-night"%}
      {%set condition="partlycloudy"%}
      {% elif datapoint.icon == "rain" %}
      {%set condition="rainy"%}
      {% elif datapoint.icon == "snow" or datapoint.icon=="sleet"%}
      {%set condition="snowy"%}
      {% elif datapoint.icon == "wind" %}
      {%set condition="windy"%}                                           
      {% endif %}
      {%set returnPoint=[{'datetime':as_local(as_datetime(datapoint.time)).strftime("%Y-%m-%dT%H:%M:%S")
      ,'temperature':datapoint.temperatureHigh, 'templow':datapoint.temperatureLow, 'condition':condition,'precipitation':datapoint.precipAccumulation
      , 'wind_bearing':datapoint.windBearing, 'wind_speed':datapoint.windSpeed}]%}
      {% set return.data=return.data+returnPoint%}
      {% endfor%}
      {{return.data}}
    forecast_hourly_template: >-
      {%set return=namespace(data=[])%}
      {%for datapoint in state_attr('sensor.forecast_hourly', 'data')%}
      {% set condition=datapoint.icon%}
      {% if datapoint.icon == "clear-day" %}
      {%set condition="sunny"%}
      {% elif datapoint.icon == "partly-cloudy-day" or datapoint.icon == "partly-cloudy-night"%}
      {%set condition="partlycloudy"%}
      {% elif datapoint.icon == "rain" %}
      {%set condition="rainy"%}
      {% elif datapoint.icon == "snow" or datapoint.icon=="sleet"%}
      {%set condition="snowy"%}
      {% elif datapoint.icon == "wind" %}
      {%set condition="windy"%}                                           
      {% endif %}
      {%set returnPoint=[{'datetime':as_local(as_datetime(datapoint.time)).strftime("%Y-%m-%dT%H:%M:%S")
      ,'temperature':datapoint.temperature,'condition':condition,'precipitation':datapoint.precipAccumulation
      , 'wind_bearing':datapoint.windBearing, 'wind_speed':datapoint.windSpeed}]%}
      {% set return.data=return.data+returnPoint%}
      {% endfor%}
      {{return.data}}

rest:
  resource_template: https://api.pirateweather.net/forecast/<API KEY>/{{ state_attr('sensor.gps', 'latitude') }},{{ state_attr('sensor.gps', 'longitude') }}?units=us&exclude=minutely&exclude=alerts&extend=hourly&extend=daily
  scan_interval: 300
  sensor:
    - name: "PW_Template_Currently"
      json_attributes_path: "$.currently"
      value_template: "OK"
      json_attributes:
        - summary
        - temperature
        - precipProbability
        - precipType
        - humidity
        - cloudCover
        - nearestStormDistance
        - precipIntensity
        - windSpeed
        - visibility
        - ozone
        - windBearing
        - pressure
        - icon
        - time
    - name: "Forecast Hourly"
      json_attributes_path: "$.hourly"
      value_template: "OK"
      json_attributes:
        - summary
        - icon
        - data
    - name: "Forecast Daily"
      json_attributes_path: "$.daily"
      value_template: "OK"
      json_attributes:
        - summary
        - icon
        - data

**Comment by mikegoubeaux** [comment] 2024-03-11 15:16
@breel007 - any chance you can post using `code blocks` - [like so](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by breel007** [comment] 2024-03-11 15:43
@mikegoubeaux good call, I think I fixed it.

**Comment by phurth** [comment] 2024-04-04 00:29
I'm not sure this works any longer since HA has moved forecasts to be retrievable via the weather.get_forecast service. I think the original request on this issue would provide the best support for out of the box HA weather functionality in the frontend. Is it not possible implement the use of a template in place of the literal `latitude` and `longitude` if PirateWeather is set up via YAML (or even better during onboarding when setting up the integration via the UI)? If not a template, then at least a sensor like `sensor.home_latitude`?

**Comment by alexander0042** [comment] 2024-04-04 20:14
I noticed your other post in #149, but figured it was easier to just reply here. I agree that it is a really irritating limitation, but as far as I've puzzled it out,  The (very clever!) approach from @breel007 doesn't rely on the integration at all, so really should template correctly. Is there a specific aspect of it that isn't working for you?

As far as a more HA specific solution, I was poking through some other integrations and while I don't see any that change the location of a Data Update Coordinator, there is one where the [scan interval is changed](https://github.com/home-assistant/core/blob/3d556f14a58b9cba8f40de4247473e24fa1eb180/homeassistant/components/airly/__init__.py#L185), so I don't know why it wouldn't be possible? This might be a good question for the discord, just to see if it's even possible. The logic of it would be easy enough- if someone defines a latitude and longitude, use that, otherwise use the GPS data.

**Comment by phurth** [comment] 2024-04-04 20:21
Can the direct web service solution work with a Lovelace card to display current conditions as well as forecast data? I was able to get it set up, and did get data into HA through the API, but was not able to get to forecast data in a weather card. Could be I did something wrong as the setup is not trivial.

**Comment by phurth** [comment] 2024-04-04 20:30
By the way - this is an awesome thing you've done with the API. Tons of data, and all well documented. Nice work!

**Comment by coldburn89** [comment] 2024-06-16 18:55
> As part of the fundamental setup of integration, I don't think possible to change the location dynamically. The issue is that it uses a weather data coordinator that is based on the lat-lon of the setup location, and it sticks with that.
> 
> However, some of the comments above get is to the same place! You can combine the "rest" platform with a weather template to produce the card manually. As a first pass, I have something like this:
> 
> ```
> 
> weather:
>   - platform: template
>     name: "Dynamic Weather"
>     # attribution: "Powered by PirateWeather"
>     condition_template: "{{ state_attr('sensor.PW_Template_Currently', 'summary') }}"
>     temperature_template: "{{ state_attr('sensor.PW_Template_Currently', 'temperature') | float }}"
>     humidity_template: "{{ state_attr('sensor.PW_Template_Currently', 'humidity') | float }}"
>     pressure_template: "{{ state_attr('sensor.PW_Template_Currently', 'pressure') }}"
>     wind_speed_template: "{{ state_attr('sensor.PW_Template_Currently', 'windSpeed') }}"
>     ozone_template: "{{ state_attr('sensor.PW_Template_Currently', 'ozone') }}"
>     visibility_template: "{{ state_attr('sensor.PW_Template_Currently', 'visibility') }}"
>     forecast_template: >-
>       [
>         {
>           {% set dat = now() + timedelta( days = 0 ) %}
>           "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
>           "temperature": "{{ state_attr('sensor.PW_Template_Daily0', 'temperatureHigh') | float }}",
>           "templow": "{{ state_attr('sensor.PW_Template_Daily0', 'temperatureLow') | float }}",
>           "precipitation": "{{ state_attr('sensor.PW_Template_Daily0', 'precipAccumulation') | float }}",
>           "condition":  "{{ state_attr('sensor.PW_Template_Daily0', 'summary') }}",
>         },
>         {
>           {% set dat = now() + timedelta( days = 1 ) %}
>           "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
>           "temperature": "{{ state_attr('sensor.PW_Template_Daily1', 'temperatureHigh') | float }}",
>           "templow": "{{ state_attr('sensor.PW_Template_Daily1', 'temperatureLow') | float }}",
>           "precipitation": "{{ state_attr('sensor.PW_Template_Daily1', 'precipAccumulation') | float }}",
>           "condition":  "{{ state_attr('sensor.PW_Template_Daily1', 'summary') }}",          
>         },
>         {
>           {% set dat = now() + timedelta( days = 2 ) %}
>           "datetime": "{{ dat.strftime("%Y-%m-%dT00:00:00Z") }}",
>           "temperature": "{{ state_attr('sensor.PW_Template_Daily2', 'temperatureHigh') | float }}",
>           "templow": "{{ state_attr('sensor.PW_Template_Daily2', 'temperatureLow') | float }}",
>           "precipitation": "{{ state_attr('sensor.PW_Template_Daily2', 'precipAccumulation') | float }}",
>           "condition":  "{{ state_attr('sensor.PW_Template_Daily2', 'summary') }}",          
>         }
>       ]
> 
> rest:
>   resource: 'https://api.pirateweather.net/forecast/<PW_API_KEY>/45.4215,-75.697'
>   scan_interval: 60
>   sensor:
>     - name: "PW_Template_Currently"
>       json_attributes_path: "$.currently"
>       value_template: "OK"
>       json_attributes:
>         - summary
>         - temperature
>         - precipProbability
>         - precipType
>         - humidity
>         - cloudCover
>         - nearestStormDistance
>         - precipIntensity
>         - windSpeed
>         - visibility
>         - ozone
>         - windBearing
>         - pressure
>     - name: "PW_Template_Daily0"
>       json_attributes_path: "$.daily.data.[0]"
>       value_template: "OK"
>       json_attributes:
>         - summary
>         - temperatureHigh
>         - temperatureLow
>         - precipAccumulation      
>     - name: "PW_Template_Daily1"
>       json_attributes_path: "$.daily.data.[1]"
>       value_template: "OK"
>       json_attributes:
>         - summary
>         - temperatureHigh
>         - temperatureLow
>         - precipAccumulation 
>     - name: "PW_Template_Daily2"
>       json_attributes_path: "$.daily.data.[2]"
>       value_template: "OK"
>       json_attributes:
>         - summary
>         - temperatureHigh
>         - temperatureLow  
>         - precipAccumulation      
> ```
> 
> I'll test this a bit more and see if I can't get the template into the location and flesh out the weather card a bit, but this absolutely should work! The only downside is that it makes we wonder if I should have just done this instead of building a whole integration...

Is this still working? I tried to copy paste this into my config, but it doesnt work :( The Entities are not being created from the template.

**Comment by alexander0042** [comment] 2024-06-17 16:12
Hmm, no reason it shouldn't work? Are you seeing an error in your logs when you reload. or just nothing.

I double checked it on my instance using this yaml, which seems to throw the occasional warning, but is otherwise working fine:
```
weather:
  - platform: template
    name: "Dynamic Weather Template"
    unique_id: "pw_template"
    attribution_template: "Powered by Pirate Weather"
    temperature_template: "{{ state_attr('sensor.PW_Template_Currently', 'temperature')}}"
    temperature_unit: "°F"
    humidity_template: "{{ state_attr('sensor.PW_Template_Currently', 'humidity') }}"
    pressure_template: "{{ state_attr('sensor.PW_Template_Currently', 'pressure') }}"
    pressure_unit: "hPa"
    wind_speed_template: "{{ state_attr('sensor.PW_Template_Currently', 'windSpeed')}}"
    wind_speed_unit: "mph"
    ozone_template: "{{ state_attr('sensor.PW_Template_Currently', 'ozone') }}"
    visibility_template: "{{ state_attr('sensor.PW_Template_Currently', 'visibility') }}"
    visibility_unit: "mi"
    precipitation_unit: "in"
    condition_template: >-
      {% if state_attr('sensor.PW_Template_Currently', 'icon') == "clear-night" %}
        clear-night
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "clear-day" %}
        sunny
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "cloudy" %}
        cloudy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "fog" %}
        fog
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "partly-cloudy-day" %}
        partlycloudy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "partly-cloudy-night" %}
        partlycloudy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "rain" %}
        rainy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "snow" %}
        snowy
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "sleet" %}
        snowy        
      {% elif state_attr('sensor.PW_Template_Currently', 'icon') == "wind" %}
        windy                                              
      {% endif %}
    forecast_daily_template: >-
      {%set return=namespace(data=[])%}
      {%for datapoint in state_attr('sensor.forecast_daily', 'data')%}
      {% set condition=datapoint.icon%}
      {% if datapoint.icon == "clear-day" %}
      {%set condition="sunny"%}
      {% elif datapoint.icon == "partly-cloudy-day" or datapoint.icon == "partly-cloudy-night"%}
      {%set condition="partlycloudy"%}
      {% elif datapoint.icon == "rain" %}
      {%set condition="rainy"%}
      {% elif datapoint.icon == "snow" or datapoint.icon=="sleet"%}
      {%set condition="snowy"%}
      {% elif datapoint.icon == "wind" %}
      {%set condition="windy"%}                                           
      {% endif %}
      {%set returnPoint=[{'datetime':as_local(as_datetime(datapoint.time)).strftime("%Y-%m-%dT%H:%M:%S")
      ,'temperature':datapoint.temperatureHigh, 'templow':datapoint.temperatureLow, 'condition':condition,'precipitation':datapoint.precipAccumulation
      , 'wind_bearing':datapoint.windBearing, 'wind_speed':datapoint.windSpeed}]%}
      {% set return.data=return.data+returnPoint%}
      {% endfor%}
      {{return.data}}
    forecast_hourly_template: >-
      {%set return=namespace(data=[])%}
      {%for datapoint in state_attr('sensor.forecast_hourly', 'data')%}
      {% set condition=datapoint.icon%}
      {% if datapoint.icon == "clear-day" %}
      {%set condition="sunny"%}
      {% elif datapoint.icon == "partly-cloudy-day" or datapoint.icon == "partly-cloudy-night"%}
      {%set condition="partlycloudy"%}
      {% elif datapoint.icon == "rain" %}
      {%set condition="rainy"%}
      {% elif datapoint.icon == "snow" or datapoint.icon=="sleet"%}
      {%set condition="snowy"%}
      {% elif datapoint.icon == "wind" %}
      {%set condition="windy"%}                                           
      {% endif %}
      {%set returnPoint=[{'datetime':as_local(as_datetime(datapoint.time)).strftime("%Y-%m-%dT%H:%M:%S")
      ,'temperature':datapoint.temperature,'condition':condition,'precipitation':datapoint.precipAccumulation
      , 'wind_bearing':datapoint.windBearing, 'wind_speed':datapoint.windSpeed}]%}
      {% set return.data=return.data+returnPoint%}
      {% endfor%}
      {{return.data}}

rest:
  - resource_template: https://api.pirateweather.net/forecast/<APIKEY>/<LAT>,<LON>?units=us&exclude=minutely
    scan_interval: 300
    sensor:
    - name: "PW_Template_Currently"
      json_attributes_path: "$.currently"
      value_template: "OK"
      json_attributes:
        - summary
        - temperature
        - precipProbability
        - precipType
        - humidity
        - cloudCover
        - nearestStormDistance
        - precipIntensity
        - windSpeed
        - visibility
        - ozone
        - windBearing
        - pressure
        - icon
        - time
    - name: "Forecast Hourly"
      json_attributes_path: "$.hourly"
      value_template: "OK"
      json_attributes:
        - summary
        - icon
        - data
    - name: "Forecast Daily"
      json_attributes_path: "$.daily"
      value_template: "OK"
      json_attributes:
        - summary
        - icon
        - data
```

**Comment by coldburn89** [comment] 2024-06-18 20:34
Also, the temperature is showing in Fahrenheit instead of Celsius (despite
the C icon) . Do you know how to fix this?

**Comment by alexander0042** [comment] 2024-06-19 13:18
Yes, you can create a new "template.yaml" with the above code in the same folder and add this line to your configuration.yaml:
`template: !include templates.yaml1`

Re: the units, you need to change this line to be `units=si':
`  - resource_template: https://api.pirateweather.net/forecast/<APIKEY>/<LAT>,<LON>?units=us&exclude=minutely`

**Comment by coldburn89** [comment] 2024-06-19 18:58
Thanks, it worked. Still have a problem: The temperatures are way off (i
live in the netherlands)
[image: image.png]
How can this be?

**Comment by alexander0042** [comment] 2024-06-19 19:32
Sorry- I can't see the picture for some reason. Can you try uploading the picture again, or elaborating on the difference?

**Comment by coldburn89** [comment] 2024-06-19 19:35
> Sorry- I can't see the picture for some reason. Can you try uploading the picture again, or elaborating on the difference?
First picture is incorrect, 2nd is correct. Looks like a formatting issue i think.
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/103142365/ee5e829f-21df-4171-859e-286421cf93dd)
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/103142365/0cf89c6d-3669-40b1-9bb2-33a2db3de9f8)

**Comment by alexander0042** [comment] 2024-06-19 20:03
Good catch! Thanks for helping to troubleshoot here

**Comment by cloneofghosts** [comment] 2024-06-21 14:54
I've updated the HA FAQ section to remove the | int on the temperature section. I'm going to close this for now but feel free to create a new issue or reply to this one if more issues pop up.

**Closed by cloneofghosts** 2024-06-21 14:54 UTC
Labels: documentation, enhancement
